#!/usr/bin/env groovy
import com.sap.piper.testutils.JenkinsController

@Library(['jenkins-library-test']) _

timeout(time: 5, unit: 'HOURS') {

    node("master") {
        stage('Init') {
            deleteDir()
            checkout scm
            if (!env.HOST) {
                error "Violated assumption: Environment variable env.HOST is not set. This must be set as the hostname."
            }
        }

        JenkinsController jenkins

        stage('Start Jenkins') {
            jenkins = new JenkinsController(this, "http://${env.HOST}")
            jenkins.waitForJenkinsStarted()
        }

        stage('Trigger Job') {
            jenkins.buildJob('infrastructure-integration-test')
        }

        stage('Wait for successful build') {
            parallel cloudFoundry: {
                jenkins.waitForSuccess('infrastructure-integration-test', 'infrastructure-integration-test')
            }, neoEnvironment: {
                jenkins.waitForSuccess('infrastructure-integration-test', 'infrastructure-integration-test-neo')
//            }, cloudFoundryCap: {
//                jenkins.waitForSuccess('infrastructure-integration-test', 'infrastructure-integration-test-cap')
            }
        }
    }
}
