jenkins:
  numExecutors: 10
jobs:
  - script: >
      multibranchPipelineJob('infrastructure-integration-test') {
          branchSources {
              git {
                  remote("https://github.com/SAP/cloud-s4-sdk-book") //fixme read from env var
                  includes('infrastructure-integration-test') // Only include one branch because the Git repo has too many branches to build, and only this branch is relevant to the test
              }
          }
      }
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "devops-docker-images-IT-cf"
              username: ${PPIPER_INFRA_IT_CF_USERNAME}
              password: ${PPIPER_INFRA_IT_CF_PASSWORD}
              description: "SAP CP Trail account."
