jenkins:
  numExecutors: 10
jobs:
  - script: >
      multibranchPipelineJob('infrastructure-integration-test') {
          branchSources {
              git {
                  remote("https://github.com/piper-validation/cloud-s4-sdk-book") // todo this should be read from the environment, unclear how to set it via environment currently
                  includes('infrastructure-integration-test*') // Only build the branches relevant for this test
              }
          }
      }
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "devops-docker-images-IT-cf"
              username: ${CX_INFRA_IT_CF_USERNAME}
              password: ${CX_INFRA_IT_CF_PASSWORD}
              description: "SAP CP Trail account."

