#!/bin/bash -eux

echo "=> Smoke-test Jenkins master"
docker run --name cx-jenkins-master-test --detach \
  -v /var/run/docker.sock:/var/run/docker.sock \
  $IMAGE_NAME

# Wait for Jenkins to boot, this might take long on DockerHub, so in doubt allow for some more time
sleep 300

# Fail when no 2xx status code is returned
docker exec cx-jenkins-master-test curl --fail http://localhost:8080/api/json
