#!/bin/bash -eux

echo "=> Smoke-test Jenkins master"
docker run --name cx-jenkins-master-test --detach --publish 8080:8080 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  $IMAGE_NAME

# Wait up to 5 minutes for Jenkins to be up and fail if it does not return 200 after this time
docker exec cx-jenkins-master-test timeout 300 bash -c "until curl --fail http://localhost:8080/api/json; do sleep 5; done"
