node("master") {
    stage('Test Jenkins Master Image') {
        sh 'echo Hello from Jenkins'
        Jenkins.instance.pluginManager.plugins.each{
            plugin -> println("${plugin.getShortName()}: ${plugin.getVersion()}")
        }
    }
}
