#!/bin/bash
if ! cp -r /cx-server/life-cycle-scripts/* /cx-server/mount/
then
    echo "There was an error in generating cx-server file"
    echo "Please make sure that you have mounted your local directory to the companion"
    echo "Example:"
    echo "         docker run -it --rm -u \$(id -u):\$(id -g) -v \${PWD}:/cx-server/mount/ ppiper/cx-server-companion:latest init-cx-server"
else
    echo "The cx-server and the server.cfg files have been successfully generated."
    echo "Execute ./cx-server help command to know more about the cx-server script"
fi
