#! /bin/sh

#start the uuid daemon
uuidd


$SAPBIN/node_modules/grunt-cli/bin/grunt --stack --no-color --gruntfile $SAPBIN/run_rfc_task.js "$@"
RC=$?

if [ -f /var/sap/data/CTS_Data.txt ]
then
   cat /var/sap/data/CTS_Data.txt
fi
exit $RC
 
