#! /bin/sh


$SAPBIN/node_modules/grunt-cli/bin/grunt --stack --no-color --gruntfile $SAPBIN/run_rfc_task.js "$@" 1>&2
RC=$?

# In case a transport request has been created this file provides the ID of
# the transport request in a json format like {"REQUESTID":"ZZZK9NNNNN"}
TRANSPORT_REQUEST_FILE="${SAPDATADIR}/CTS_Data.txt"
TRACE_FILE=dev_rfc.trc

if [ -f "${TRACE_FILE}" ]
then
  cat "${TRACE_FILE}" 1>&2
fi

if [ -f "${TRANSPORT_REQUEST_FILE}" ]
then
   cat "${TRANSPORT_REQUEST_FILE}"
fi
exit $RC
